#version: '3.8'

services:
  http:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src/wordpress:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script
    networks:
      - wp-network

  script:
    image: php:8.1-fpm
    volumes:
      - ./src/wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - wp-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
    driver: bridge
