version: '3.8'

services:
  http:
    image: nginx:latest
    container_name: http
    ports:
      - "8081:80"
    volumes:
      - ./src:/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script
      - db

  script:
    image: php:7.4-fpm
    container_name: script
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
